services:
  backend:
    build: .
    env_file:
      - .env
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    environment:
      - PYTHONUNBUFFERED=1
      - REDIS_HOST=redis
    depends_on:
      - redis

  worker:
    build: .
    command: python manage.py rqworker default
    env_file:
      - .env
    volumes:
      - .:/app
    environment:
      - PYTHONUNBUFFERED=1
      - REDIS_HOST=redis
    depends_on:
      - redis

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"

  frontend:
    build: ../checkers-react
    ports:
      - "5173:5173"
    volumes:
      - ../checkers-react:/app
      - /app/node_modules
    environment:
      - WATCHPACK_POLLING=true
    depends_on:
      - backend
