# Generated by Django 6.0.4 on 2026-04-15 16:31

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('board', models.JSONField()),
                ('current_turn', models.CharField(choices=[('white', 'White'), ('black', 'Black')], max_length=10)),
                ('status', models.CharField(choices=[('active', 'Active'), ('finished', 'Finished')], default='active', max_length=10)),
                ('winner', models.CharField(blank=True, choices=[('white', 'White'), ('black', 'Black')], max_length=10, null=True)),
                ('move_count', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='MoveEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('player_side', models.CharField(choices=[('white', 'White'), ('black', 'Black')], max_length=10)),
                ('from_pos', models.JSONField()),
                ('to_pos', models.JSONField()),
                ('is_jump', models.BooleanField(default=False)),
                ('captured_pos', models.JSONField(blank=True, null=True)),
                ('is_promoted', models.BooleanField(default=False)),
                ('board_before', models.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='moves', to='games.game')),
            ],
            options={
                'ordering': ['created_at', 'id'],
            },
        ),
    ]
